"""
Calorie-Diversity Interactive Hover Map
=======================================
Generates a full-screen Folium map with dropdown to switch between:
  ABI, Kcal/ha, Quadrant category, Food crop kcal share.
Hover shows all diversity indices, kcal metrics, quadrant, top crops, irrigation.

Usage:
    python scripts/63_calorie_diversity_hover_map.py

Requires:
    outputs/crop_diversity_analysis/district_diversity_calorie_merged.csv
    (generated by script 62)

Output:
    outputs/crop_diversity_analysis/calorie_diversity_hover_map.html
"""

import json
import re
import webbrowser
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd
import folium
from thefuzz import fuzz

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE = Path(__file__).resolve().parent.parent
CSV_PATH = BASE / "outputs" / "crop_diversity_analysis" / "district_diversity_calorie_merged.csv"
SHP_PATH = BASE / "Package_Maps_Share_20251120_FINAL" / "shapefiles" / "in_district.shp"
OUT_PATH = BASE / "outputs" / "crop_diversity_analysis" / "calorie_diversity_hover_map.html"

# ---------------------------------------------------------------------------
# 1. Load data
# ---------------------------------------------------------------------------
print("Loading data...")
df = pd.read_csv(CSV_PATH)
gdf = gpd.read_file(SHP_PATH)

print(f"  CSV districts: {len(df)}")
print(f"  Shapefile districts: {len(gdf)}")

# ---------------------------------------------------------------------------
# 2. District matching (same approach as script 60)
# ---------------------------------------------------------------------------
def normalize(s):
    s = str(s).upper().strip()
    s = s.replace("&", "AND")
    s = re.sub(r"[^A-Z0-9 ]", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

MANUAL_MAP = {
    ("ANDAMAN AND NICOBAR", "NICOBARS"): ("ANDAMAN AND NICOBAR ISLANDS", "NICOBARS"),
    ("ANDAMAN AND NICOBAR", "NORTH AND MIDDLE ANDAMAN"): ("ANDAMAN AND NICOBAR ISLANDS", "NORTH AND MIDDLE ANDAMAN"),
    ("ANDAMAN AND NICOBAR", "SOUTH ANDAMAN"): ("ANDAMAN AND NICOBAR ISLANDS", "SOUTH ANDAMANS"),
    ("DADRA AND NAGAR HAVE", "DADRA AND NAGAR HAVELI"): ("THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU", "DADRA AND NAGAR HAVELI"),
    ("DAMAN AND DIU", "DAMAN"): ("THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU", "DAMAN"),
    ("DAMAN AND DIU", "DIU"): ("THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU", "DIU"),
    ("ANDHRA PRADESH", "SRI POTTI SRIRAMULU NELL"): ("ANDHRA PRADESH", "SRI POTTI SRIRAMULU NELLORE"),
    ("ANDHRA PRADESH", "VISAKHAPATNAM"): ("ANDHRA PRADESH", "VISAKHAPATANAM"),
    ("ANDHRA PRADESH", "YSR"): ("ANDHRA PRADESH", "KADAPA"),
    ("ARUNACHAL PRADESH", "LEPA RADA"): ("ARUNACHAL PRADESH", "LEPARADA"),
    ("ASSAM", "KAMRUP METROPOLITAN"): ("ASSAM", "KAMRUP METRO"),
    ("ASSAM", "MORIGAON"): ("ASSAM", "MARIGAON"),
    ("BIHAR", "PURBA CHAMPARAN"): ("BIHAR", "PURBI CHAMPARAN"),
    ("CHHATTISGARH", "BAMETARA"): ("CHHATTISGARH", "BEMETARA"),
    ("CHHATTISGARH", "GARIABAND"): ("CHHATTISGARH", "GARIYABAND"),
    ("CHHATTISGARH", "JANJGIR CHAMPA"): ("CHHATTISGARH", "JANJGIRCHAMPA"),
    ("CHHATTISGARH", "KABEERDHAM"): ("CHHATTISGARH", "KABIRDHAM"),
    ("CHHATTISGARH", "KORIYA"): ("CHHATTISGARH", "KOREA"),
    ("CHHATTISGARH", "UTTAR BASTAR KANKER"): ("CHHATTISGARH", "KANKER"),
    ("GUJARAT", "CHOTA UDAIPUR"): ("GUJARAT", "CHHOTAUDEPUR"),
    ("GUJARAT", "THE DANGS"): ("GUJARAT", "DANG"),
    ("HARYANA", "GURUGRAM"): ("HARYANA", "GURGAON"),
    ("HARYANA", "NUH"): ("HARYANA", "MEWAT"),
    ("JAMMU AND KASHMIR", "BANDIPORE"): ("JAMMU AND KASHMIR", "BANDIPORA"),
    ("JAMMU AND KASHMIR", "BARAMULA"): ("JAMMU AND KASHMIR", "BARAMULLA"),
    ("JAMMU AND KASHMIR", "PUNCH"): ("JAMMU AND KASHMIR", "POONCH"),
    ("JAMMU AND KASHMIR", "RAJOURI"): ("JAMMU AND KASHMIR", "RAJAURI"),
    ("JAMMU AND KASHMIR", "SHUPIYAN"): ("JAMMU AND KASHMIR", "SHOPIAN"),
    ("JHARKHAND", "KODARMA"): ("JHARKHAND", "KODERMA"),
    ("JHARKHAND", "PASHCHIMI SINGHBHUM"): ("JHARKHAND", "WEST SINGHBHUM"),
    ("JHARKHAND", "PURBI SINGHBHUM"): ("JHARKHAND", "EAST SINGHBUM"),
    ("JHARKHAND", "SAHIBGANJ"): ("JHARKHAND", "SAHEBGANJ"),
    ("JHARKHAND", "SARAIKELAKHARSAWAN"): ("JHARKHAND", "SARAIKELA KHARSAWAN"),
    ("KARNATAKA", "BANGALORE"): ("KARNATAKA", "BANGALORE RURAL"),
    ("KARNATAKA", "BENGALURU RURAL"): ("KARNATAKA", "BANGALORE RURAL"),
    ("KARNATAKA", "DAVANAGERE"): ("KARNATAKA", "DAVANGERE"),
    ("KARNATAKA", "YADGIR"): ("KARNATAKA", "YADAGIRI"),
    ("LADAKH", "LEH"): ("LADAKH", "LEH LADAKH"),
    ("MADHYA PRADESH", "EAST NIMAR"): ("MADHYA PRADESH", "KHANDWA"),
    ("MADHYA PRADESH", "WEST NIMAR"): ("MADHYA PRADESH", "KHARGONE"),
    ("MADHYA PRADESH", "NARSIMHAPUR"): ("MADHYA PRADESH", "NARSINGHPUR"),
    ("MAHARASHTRA", "AHMADNAGAR"): ("MAHARASHTRA", "AHMEDNAGAR"),
    ("MAHARASHTRA", "BID"): ("MAHARASHTRA", "BEED"),
    ("MAHARASHTRA", "BULDANA"): ("MAHARASHTRA", "BULDHANA"),
    ("MAHARASHTRA", "GONDIYA"): ("MAHARASHTRA", "GONDIA"),
    ("MAHARASHTRA", "RAIGARH"): ("MAHARASHTRA", "RAIGAD"),
    ("MEGHALAYA", "RIBHOI"): ("MEGHALAYA", "RI BHOI"),
    ("ODISHA", "BAUDH"): ("ODISHA", "BOUDH"),
    ("ODISHA", "DEBAGARH"): ("ODISHA", "DEOGARH"),
    ("ODISHA", "NABARANGAPUR"): ("ODISHA", "NABARANGPUR"),
    ("ODISHA", "SUBARNAPUR"): ("ODISHA", "SONEPUR"),
    ("PUDUCHERRY", "PUDUCHERRY"): ("PUDUCHERRY", "PONDICHERRY"),
    ("PUNJAB", "FIROZPUR"): ("PUNJAB", "FIROZEPUR"),
    ("PUNJAB", "SAHIBZADA AJIT SINGH NAG"): ("PUNJAB", "SAS NAGAR"),
    ("PUNJAB", "SRI MUKTSAR SAHIB"): ("PUNJAB", "MUKTSAR"),
    ("RAJASTHAN", "CHITTAURGARH"): ("RAJASTHAN", "CHITTORGARH"),
    ("RAJASTHAN", "DHAULPUR"): ("RAJASTHAN", "DHOLPUR"),
    ("RAJASTHAN", "JALOR"): ("RAJASTHAN", "JALORE"),
    ("RAJASTHAN", "JHUNJHUNUN"): ("RAJASTHAN", "JHUNJHUNU"),
    ("SIKKIM", "EAST DISTRICT"): ("SIKKIM", "GANGTOK"),
    ("SIKKIM", "NORTH DISTRICT"): ("SIKKIM", "MANGAN"),
    ("SIKKIM", "SOUTH DISTRICT"): ("SIKKIM", "NAMCHI"),
    ("SIKKIM", "WEST DISTRICT"): ("SIKKIM", "GYALSHING"),
    ("TAMIL NADU", "KANCHEEPURAM"): ("TAMIL NADU", "KANCHIPURAM"),
    ("TAMIL NADU", "THOOTHUKKUDI"): ("TAMIL NADU", "TUTICORIN"),
    ("TAMIL NADU", "VILUPPURAM"): ("TAMIL NADU", "VILLUPURAM"),
    ("TELANGANA", "BHADRADRI KOTHAGUDEM"): ("TELANGANA", "BHADRADRI"),
    ("TELANGANA", "JOGULAMBA GADWAL"): ("TELANGANA", "JOGULAMBA"),
    ("TELANGANA", "KUMURAM BHEEM ASIFABAD"): ("TELANGANA", "KOMARAM BHEEM ASIFABAD"),
    ("TELANGANA", "NARAYANPET"): ("TELANGANA", "NARAYANAPET"),
    ("TELANGANA", "RAJANNA SIRCILLA"): ("TELANGANA", "RAJANNA"),
    ("TELANGANA", "RANGA REDDY"): ("TELANGANA", "RANGAREDDI"),
    ("TELANGANA", "WARANGAL RURAL"): ("TELANGANA", "WARANGAL"),
    ("TELANGANA", "WARANGAL URBAN"): ("TELANGANA", "HANUMAKONDA"),
    ("TELANGANA", "YADADRI BHUVANAGIRI"): ("TELANGANA", "YADADRI"),
    ("TRIPURA", "SIPAHIJALA"): ("TRIPURA", "SEPAHIJALA"),
    ("TRIPURA", "UNOKOTI"): ("TRIPURA", "UNAKOTI"),
    ("UTTAR PRADESH", "BARA BANKI"): ("UTTAR PRADESH", "BARABANKI"),
    ("UTTAR PRADESH", "BHADOHI"): ("UTTAR PRADESH", "SANT RAVIDAS NAGAR"),
    ("UTTAR PRADESH", "KUSHINAGAR"): ("UTTAR PRADESH", "KUSHI NAGAR"),
    ("UTTAR PRADESH", "MAHRAJGANJ"): ("UTTAR PRADESH", "MAHARAJGANJ"),
    ("UTTAR PRADESH", "PRAYAGRAJ"): ("UTTAR PRADESH", "ALLAHABAD"),
    ("UTTAR PRADESH", "SANT KABIR NAGAR"): ("UTTAR PRADESH", "SANT KABEER NAGAR"),
    ("UTTAR PRADESH", "SHRAWASTI"): ("UTTAR PRADESH", "SHRAVASTI"),
    ("UTTAR PRADESH", "SIDDHARTHNAGAR"): ("UTTAR PRADESH", "SIDDHARTH NAGAR"),
    ("UTTARAKHAND", "GARHWAL"): ("UTTARAKHAND", "PAURI GARHWAL"),
    ("UTTARAKHAND", "HARDWAR"): ("UTTARAKHAND", "HARIDWAR"),
    ("UTTARAKHAND", "RUDRAPRAYAG"): ("UTTARAKHAND", "RUDRA PRAYAG"),
    ("UTTARAKHAND", "UDHAM SINGH NAGAR"): ("UTTARAKHAND", "UDAM SINGH NAGAR"),
    ("UTTARAKHAND", "UTTARKASHI"): ("UTTARAKHAND", "UTTAR KASHI"),
    ("WEST BENGAL", "COOCH BEHAR"): ("WEST BENGAL", "COOCHBEHAR"),
    ("WEST BENGAL", "DARJILING"): ("WEST BENGAL", "DARJEELING"),
    ("WEST BENGAL", "MEDINIPUR WEST"): ("WEST BENGAL", "PASHCHIM MEDINIPUR"),
    ("WEST BENGAL", "NORTH TWENTY FOUR PARGAN"): ("WEST BENGAL", "NORTH 24 PARGANAS"),
    ("WEST BENGAL", "PURULIYA"): ("WEST BENGAL", "PURULIA"),
    ("WEST BENGAL", "SOUTH TWENTY FOUR PARGAN"): ("WEST BENGAL", "SOUTH 24 PARGANAS"),
}

# Build CSV lookup
csv_keys = {}
for i, row in df.iterrows():
    st = normalize(row["state_name"])
    dt = normalize(row["district_name"])
    csv_keys[(st, dt)] = i

# Match shapefile districts
print("Matching shapefile districts...")
match_col = [None] * len(gdf)
exact = manual = fuzzy_cnt = unmatched = 0

for idx, row in gdf.iterrows():
    shp_st = normalize(row["stname"])
    shp_dt = normalize(row["dtname"])

    if (shp_st, shp_dt) in csv_keys:
        match_col[idx] = csv_keys[(shp_st, shp_dt)]
        exact += 1
        continue

    mapped = MANUAL_MAP.get((shp_st, shp_dt))
    if mapped and mapped in csv_keys:
        match_col[idx] = csv_keys[mapped]
        manual += 1
        continue

    district_only = [(k, v) for k, v in csv_keys.items() if k[1] == shp_dt]
    if len(district_only) == 1:
        match_col[idx] = district_only[0][1]
        exact += 1
        continue

    best_score = 0
    best_idx_val = None
    same_state = [(k, v) for k, v in csv_keys.items() if fuzz.ratio(k[0], shp_st) > 80]
    for (csv_st, csv_dt), csv_idx_val in same_state:
        score = fuzz.ratio(shp_dt, csv_dt)
        if score > best_score:
            best_score = score
            best_idx_val = csv_idx_val
    if best_score < 85:
        for (csv_st, csv_dt), csv_idx_val in csv_keys.items():
            score = fuzz.ratio(shp_dt, csv_dt)
            if score > best_score:
                best_score = score
                best_idx_val = csv_idx_val
    if best_score >= 85:
        match_col[idx] = best_idx_val
        fuzzy_cnt += 1
    else:
        unmatched += 1

gdf["csv_idx"] = match_col
total_matched = exact + manual + fuzzy_cnt
print(f"  Exact: {exact}, Manual: {manual}, Fuzzy: {fuzzy_cnt}, Unmatched: {unmatched}")
print(f"  Coverage: {total_matched}/{len(gdf)} ({total_matched/len(gdf)*100:.1f}%)")

# ---------------------------------------------------------------------------
# 3. Merge data into GeoDataFrame
# ---------------------------------------------------------------------------
merge_cols = [
    "state_name", "district_name",
    "shannon_index", "simpson_index", "crop_richness", "agro_biodiversity_index",
    "irrigation_regime", "dominant_crop", "dominant_crop_share",
    "share_cereals", "share_pulses", "share_oilseeds",
    "total_kcal_annual", "food_crop_kcal_annual", "kcal_per_hectare",
    "food_crop_kcal_share", "kcal_diversity_quadrant",
    "kcal_diversity_quadrant_ex_coconut",
    "coconut_dominant", "coconut_kcal_share",
    "cereal_kcal_share", "pulse_kcal_share", "oilseed_kcal_share",
    "sugar_kcal_share", "vegetable_kcal_share", "fruit_kcal_share",
    "top_crops_by_kcal",
]

# Ensure columns exist in df
merge_cols = [c for c in merge_cols if c in df.columns]

for col in merge_cols:
    gdf[col] = None

for idx, row in gdf.iterrows():
    csv_idx_val = row["csv_idx"]
    if csv_idx_val is not None and not pd.isna(csv_idx_val):
        csv_idx_val = int(csv_idx_val)
        for col in merge_cols:
            gdf.at[idx, col] = df.at[csv_idx_val, col]

gdf["irrigation_regime"] = gdf["irrigation_regime"].fillna("Unknown")
gdf["kcal_diversity_quadrant"] = gdf["kcal_diversity_quadrant"].fillna("No Data")
gdf["kcal_diversity_quadrant_ex_coconut"] = gdf["kcal_diversity_quadrant_ex_coconut"].fillna("No Data")
gdf["coconut_dominant"] = gdf["coconut_dominant"].fillna(False)
gdf["coconut_kcal_share"] = gdf["coconut_kcal_share"].fillna(0)

# Simplify geometries
print("Simplifying geometries...")
gdf["geometry"] = gdf["geometry"].simplify(tolerance=0.01, preserve_topology=True)
gdf = gdf.to_crs(epsg=4326)

# ---------------------------------------------------------------------------
# 4. Build Folium map
# ---------------------------------------------------------------------------
print("Building map...")

def fmt_pct(val):
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return "N/A"
    return f"{float(val) * 100:.1f}%"

def fmt_num(val, fmt=".2f"):
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return "N/A"
    return f"{float(val):{fmt}}"

def fmt_kcal(val):
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return "N/A"
    v = float(val)
    if abs(v) >= 1e9:
        return f"{v/1e9:.1f}B"
    elif abs(v) >= 1e6:
        return f"{v/1e6:.1f}M"
    elif abs(v) >= 1e3:
        return f"{v/1e3:.0f}K"
    else:
        return f"{v:,.0f}"

# Index configs for the dropdown
INDEX_CONFIG = {
    "agro_biodiversity_index": {"label": "Agro-Biodiversity Index", "cmap": "YlGnBu", "fmt": ".2f", "type": "continuous"},
    "shannon_index": {"label": "Shannon Index", "cmap": "YlGnBu", "fmt": ".2f", "type": "continuous"},
    "simpson_index": {"label": "Simpson Index", "cmap": "YlGnBu", "fmt": ".2f", "type": "continuous"},
    "crop_richness": {"label": "Crop Richness", "cmap": "YlGnBu", "fmt": ".0f", "type": "continuous"},
    "kcal_per_hectare": {"label": "Kcal/ha", "cmap": "YlOrRd", "fmt": ",.0f", "type": "continuous"},
    "kcal_diversity_quadrant": {"label": "Diversity-Calorie Quadrant", "cmap": None, "fmt": None, "type": "categorical"},
    "food_crop_kcal_share": {"label": "Food Crop Kcal Share", "cmap": "RdYlGn", "fmt": ".1%", "type": "continuous"},
}

# Color scales for continuous variables
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

def get_color_scale(values, cmap_name, n_bins=8, log_scale=False):
    valid = [v for v in values if v is not None and not (isinstance(v, float) and np.isnan(v))]
    if not valid:
        return [], [], False
    vmin, vmax = min(valid), max(valid)
    if vmin == vmax:
        vmax = vmin + 1
    if log_scale and vmin > 0:
        edges = np.logspace(np.log10(max(vmin, 1)), np.log10(vmax), n_bins + 1)
    else:
        edges = np.linspace(vmin, vmax, n_bins + 1)
        log_scale = False
    cmap = plt.get_cmap(cmap_name, n_bins)
    colors = [mcolors.to_hex(cmap(i)) for i in range(n_bins)]
    return edges, colors, log_scale

# Quadrant colors
QUAD_COLORS = {
    "Diverse & Calorie-Rich": "#2166ac",
    "Monoculture Breadbasket": "#ef8a62",
    "Diverse & Calorie-Poor": "#67a9cf",
    "Vulnerable": "#d6604d",
    "No Data": "#d3d3d3",
}

# Build tooltip HTML
def build_tooltip_html(row):
    name = row.get("district_name") or row.get("dtname") or "Unknown"
    state = row.get("state_name") or row.get("stname") or "Unknown"
    irr = row.get("irrigation_regime") or "Unknown"
    dom_crop = row.get("dominant_crop") or "N/A"
    dom_share = fmt_pct(row.get("dominant_crop_share"))
    quadrant = row.get("kcal_diversity_quadrant") or "N/A"

    shannon = fmt_num(row.get("shannon_index"))
    simpson = fmt_num(row.get("simpson_index"))
    richness = fmt_num(row.get("crop_richness"), ".0f")
    abi = fmt_num(row.get("agro_biodiversity_index"))

    kcal_ha = fmt_kcal(row.get("kcal_per_hectare"))
    total_kcal = fmt_kcal(row.get("total_kcal_annual"))
    food_share = fmt_pct(row.get("food_crop_kcal_share"))

    cereals = fmt_pct(row.get("share_cereals"))
    pulses = fmt_pct(row.get("share_pulses"))
    oilseeds = fmt_pct(row.get("share_oilseeds"))

    cereal_kcal = fmt_pct(row.get("cereal_kcal_share"))
    pulse_kcal = fmt_pct(row.get("pulse_kcal_share"))
    oilseed_kcal = fmt_pct(row.get("oilseed_kcal_share"))

    top_crops = row.get("top_crops_by_kcal") or "N/A"
    # Truncate long crop names and limit total length
    if isinstance(top_crops, str) and len(top_crops) > 60:
        top_crops = top_crops[:57] + "..."

    quad_color = QUAD_COLORS.get(quadrant, "#999")

    # Coconut badge
    coconut_dom = row.get("coconut_dominant")
    coconut_share = row.get("coconut_kcal_share")
    coconut_badge = ""
    if coconut_dom and str(coconut_dom).lower() not in ("false", "0", "nan", "none", ""):
        pct = fmt_pct(coconut_share)
        coconut_badge = f'''
      <div style="display:inline-block; padding:2px 8px; border-radius:3px; background:#8B4513; color:white; font-size:11px; font-weight:600; margin-bottom:4px;">
        &#x1F965; Coconut-dominant ({pct} kcal)
      </div>'''

    return f"""
    <div style="font-family:'Segoe UI',Arial,sans-serif; font-size:13px; line-height:1.5; min-width:280px; max-width:340px;">
      <div style="font-size:15px; font-weight:700; color:#1a1a2e; border-bottom:2px solid #0f3460; padding-bottom:4px; margin-bottom:6px;">
        {name}
      </div>
      <div style="color:#555; font-size:12px; margin-bottom:4px;">{state}</div>
      <div style="display:inline-block; padding:2px 8px; border-radius:3px; background:{quad_color}; color:white; font-size:11px; font-weight:600; margin-bottom:8px;">
        {quadrant}
      </div>{coconut_badge}
      <div style="color:#666; font-size:11px; margin-bottom:6px;">Irrigation: {irr}</div>

      <table style="width:100%; font-size:12px; border-collapse:collapse;">
        <tr style="background:#e8f4f8;"><td colspan="4" style="padding:3px 6px; font-weight:700; color:#0f3460;">Diversity Indices</td></tr>
        <tr><td style="padding:2px 6px;">Shannon</td><td style="text-align:right; font-weight:600;">{shannon}</td>
            <td style="padding:2px 6px;">Simpson</td><td style="text-align:right; font-weight:600;">{simpson}</td></tr>
        <tr style="background:#f8f8f8;"><td style="padding:2px 6px;">Richness</td><td style="text-align:right; font-weight:600;">{richness}</td>
            <td style="padding:2px 6px;">ABI</td><td style="text-align:right; font-weight:600;">{abi}</td></tr>
      </table>

      <table style="width:100%; font-size:12px; border-collapse:collapse; margin-top:6px;">
        <tr style="background:#fff3e0;"><td colspan="4" style="padding:3px 6px; font-weight:700; color:#e65100;">Calorie Metrics</td></tr>
        <tr><td style="padding:2px 6px;">Kcal/ha</td><td style="text-align:right; font-weight:600;">{kcal_ha}</td>
            <td style="padding:2px 6px;">Total Kcal</td><td style="text-align:right; font-weight:600;">{total_kcal}</td></tr>
        <tr style="background:#f8f8f8;"><td style="padding:2px 6px;">Food Kcal%</td><td style="text-align:right; font-weight:600;">{food_share}</td>
            <td colspan="2"></td></tr>
      </table>

      <table style="width:100%; font-size:11px; border-collapse:collapse; margin-top:6px;">
        <tr style="background:#e8f5e9;"><td colspan="4" style="padding:3px 6px; font-weight:700; color:#2e7d32;">Kcal Shares by Category</td></tr>
        <tr><td style="padding:1px 6px;">Cereals</td><td style="text-align:right;">{cereal_kcal}</td>
            <td style="padding:1px 6px;">Pulses</td><td style="text-align:right;">{pulse_kcal}</td></tr>
        <tr style="background:#f8f8f8;"><td style="padding:1px 6px;">Oilseeds</td><td style="text-align:right;">{oilseed_kcal}</td>
            <td colspan="2"></td></tr>
      </table>

      <div style="margin-top:8px; padding-top:6px; border-top:1px solid #ddd; font-size:11px; max-width:320px;">
        <div style="font-weight:600; color:#1a1a2e; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;">Dominant: {dom_crop} ({dom_share})</div>
        <div style="color:#666; margin-top:3px; font-size:10px; word-wrap:break-word; overflow-wrap:break-word; max-width:310px;">Top kcal crops: {top_crops}</div>
      </div>
    </div>
    """

# Build GeoJSON features
print("Preparing GeoJSON features...")
features = []
for idx, row in gdf.iterrows():
    geom = row["geometry"]
    if geom is None or geom.is_empty:
        continue
    props = {
        "tooltip": build_tooltip_html(row),
        "district_name": str(row.get("district_name") or row.get("dtname") or ""),
        "state_name": str(row.get("state_name") or row.get("stname") or ""),
        "irrigation_regime": str(row.get("irrigation_regime") or "Unknown"),
        "kcal_diversity_quadrant": str(row.get("kcal_diversity_quadrant") or "No Data"),
        "kcal_diversity_quadrant_ex_coconut": str(row.get("kcal_diversity_quadrant_ex_coconut") or "No Data"),
        "coconut_dominant": bool(row.get("coconut_dominant") and str(row.get("coconut_dominant")).lower() not in ("false", "0", "nan", "none", "")),
        "coconut_kcal_share": float(row.get("coconut_kcal_share") or 0),
    }

    # Add numeric values for all continuous indices
    for idx_key in ["agro_biodiversity_index", "shannon_index", "simpson_index",
                     "crop_richness", "kcal_per_hectare", "food_crop_kcal_share"]:
        val = row.get(idx_key)
        if val is not None and not (isinstance(val, float) and np.isnan(val)):
            try:
                props[idx_key] = float(val)
            except (ValueError, TypeError):
                props[idx_key] = None
        else:
            props[idx_key] = None

    feat = {
        "type": "Feature",
        "geometry": json.loads(gpd.GeoSeries([geom]).to_json())["features"][0]["geometry"],
        "properties": props,
    }
    features.append(feat)

geojson_data = {"type": "FeatureCollection", "features": features}
print(f"  {len(features)} features prepared")

# Compute color scales for continuous indices
color_scales = {}
log_scale_keys = set()
for idx_key in ["agro_biodiversity_index", "shannon_index", "simpson_index",
                 "crop_richness", "kcal_per_hectare", "food_crop_kcal_share"]:
    vals = [f["properties"][idx_key] for f in features]
    cfg = INDEX_CONFIG[idx_key]
    use_log = (idx_key == "kcal_per_hectare")
    edges, colors, is_log = get_color_scale(vals, cfg["cmap"], log_scale=use_log)
    color_scales[idx_key] = (edges, colors)
    if is_log:
        log_scale_keys.add(idx_key)
    for f in features:
        val = f["properties"][idx_key]
        if val is None or (isinstance(val, float) and np.isnan(val)):
            f["properties"][f"color_{idx_key}"] = "#d3d3d3"
        else:
            assigned = "#d3d3d3"
            for i in range(len(edges) - 1):
                if val <= edges[i + 1]:
                    assigned = colors[i]
                    break
            else:
                assigned = colors[-1]
            f["properties"][f"color_{idx_key}"] = assigned

# Assign quadrant colors
for f in features:
    q = f["properties"]["kcal_diversity_quadrant"]
    f["properties"]["color_kcal_diversity_quadrant"] = QUAD_COLORS.get(q, "#d3d3d3")
    q_ex = f["properties"]["kcal_diversity_quadrant_ex_coconut"]
    f["properties"]["color_kcal_diversity_quadrant_ex_coconut"] = QUAD_COLORS.get(q_ex, "#d3d3d3")

# ---------------------------------------------------------------------------
# 5. Create Folium map
# ---------------------------------------------------------------------------
m = folium.Map(
    location=[22.5, 82.0],
    zoom_start=5,
    tiles=None,
    prefer_canvas=True,
)

folium.TileLayer(
    tiles="https://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}{r}.png",
    attr="CartoDB",
    name="Light",
    control=False,
).add_to(m)

geojson_js = json.dumps(geojson_data)

# Color scales JSON
color_scales_dict = {}
for k, v in color_scales.items():
    color_scales_dict[k] = {"edges": [float(x) for x in v[0]], "colors": v[1]}
color_scales_js = json.dumps(color_scales_dict)

quad_colors_js = json.dumps(QUAD_COLORS)

custom_html = f"""
<style>
  .control-panel {{
    position: fixed;
    top: 12px;
    left: 60px;
    z-index: 1000;
    background: rgba(255,255,255,0.95);
    padding: 12px 16px;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.15);
    font-family: 'Segoe UI', Arial, sans-serif;
    font-size: 13px;
  }}
  .control-panel label {{
    font-weight: 600;
    color: #1a1a2e;
    display: block;
    margin-bottom: 4px;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }}
  .control-panel select {{
    width: 220px;
    padding: 4px 8px;
    margin-bottom: 8px;
    border: 1px solid #ccc;
    border-radius: 4px;
    font-size: 13px;
    background: white;
  }}
  .map-title {{
    position: fixed;
    top: 12px;
    left: 50%;
    transform: translateX(-50%);
    z-index: 1000;
    background: rgba(255,255,255,0.92);
    padding: 8px 24px;
    border-radius: 6px;
    box-shadow: 0 2px 6px rgba(0,0,0,0.12);
    font-family: 'Segoe UI', Arial, sans-serif;
    font-size: 16px;
    font-weight: 700;
    color: #1a1a2e;
    white-space: nowrap;
  }}
  .legend-panel {{
    position: fixed;
    bottom: 30px;
    right: 20px;
    z-index: 1000;
    background: rgba(255,255,255,0.95);
    padding: 10px 14px;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.15);
    font-family: 'Segoe UI', Arial, sans-serif;
    font-size: 11px;
    max-height: 300px;
    overflow-y: auto;
  }}
  .legend-panel .legend-title {{
    font-weight: 700;
    margin-bottom: 6px;
    color: #1a1a2e;
  }}
  .legend-item {{
    display: flex;
    align-items: center;
    margin: 2px 0;
  }}
  .legend-swatch {{
    width: 20px;
    height: 14px;
    margin-right: 6px;
    border: 1px solid #ccc;
    flex-shrink: 0;
  }}
  .district-tooltip {{
    background: white;
    border: 1px solid #ccc;
    border-radius: 6px;
    padding: 0;
    box-shadow: 0 3px 10px rgba(0,0,0,0.15);
  }}
  .district-tooltip .leaflet-tooltip-content {{
    margin: 0;
    padding: 8px;
  }}
</style>

<div class="map-title" id="mapTitle">Calorie-Diversity Analysis: Agro-Biodiversity Index</div>

<div class="control-panel">
  <label>Display Layer</label>
  <select id="indexSelect" onchange="updateMap()">
    <option value="agro_biodiversity_index">Agro-Biodiversity Index</option>
    <option value="shannon_index">Shannon Index</option>
    <option value="simpson_index">Simpson Index</option>
    <option value="crop_richness">Crop Richness</option>
    <option value="kcal_per_hectare">Kcal/ha</option>
    <option value="kcal_diversity_quadrant">Diversity-Calorie Quadrant</option>
    <option value="food_crop_kcal_share">Food Crop Kcal Share</option>
  </select>
  <label>Irrigation Filter</label>
  <select id="irrSelect" onchange="updateMap()">
    <option value="All">All Districts</option>
    <option value="Rainfed">Rainfed</option>
    <option value="Semi-Irrigated">Semi-Irrigated</option>
    <option value="Irrigated">Irrigated</option>
  </select>
  <label>Quadrant Mode</label>
  <select id="coconutSelect" onchange="updateMap()">
    <option value="including">Including Coconut</option>
    <option value="excluding">Excluding Coconut</option>
  </select>
</div>

<div class="legend-panel" id="legendPanel"></div>

<script>
var geojsonData = {geojson_js};
var colorScales = {color_scales_js};
var quadColors = {quad_colors_js};

var indexLabels = {{
  "agro_biodiversity_index": "Agro-Biodiversity Index",
  "shannon_index": "Shannon Index",
  "simpson_index": "Simpson Index",
  "crop_richness": "Crop Richness",
  "kcal_per_hectare": "Kcal/ha",
  "kcal_diversity_quadrant": "Diversity-Calorie Quadrant",
  "food_crop_kcal_share": "Food Crop Kcal Share"
}};

var currentLayer = null;

function valToColor(val, edges, colors) {{
  if (val === null || val === undefined) return "#d3d3d3";
  for (var i = 0; i < edges.length - 1; i++) {{
    if (val <= edges[i+1]) return colors[i];
  }}
  return colors[colors.length - 1];
}}

function fmtKcal(val) {{
  if (val === null || val === undefined) return "N/A";
  var v = Math.abs(val);
  if (v >= 1e9) return (val/1e9).toFixed(1) + "B";
  if (v >= 1e6) return (val/1e6).toFixed(1) + "M";
  if (v >= 1e3) return Math.round(val/1e3) + "K";
  return Math.round(val).toLocaleString();
}}
function formatNum(val, isKcal) {{
  if (val === null || val === undefined) return "N/A";
  if (isKcal) return fmtKcal(val);
  return val.toFixed(2);
}}

function updateLegend(indexKey) {{
  var html = '<div class="legend-title">' + indexLabels[indexKey] + '</div>';

  if (indexKey === "kcal_diversity_quadrant") {{
    for (var q in quadColors) {{
      html += '<div class="legend-item"><div class="legend-swatch" style="background:' + quadColors[q] + '"></div>' + q + '</div>';
    }}
  }} else {{
    var cs = colorScales[indexKey];
    if (!cs) return;
    var isKcal = (indexKey === "kcal_per_hectare");
    var isPct = (indexKey === "food_crop_kcal_share");
    var isInt = (indexKey === "crop_richness");
    for (var i = 0; i < cs.colors.length; i++) {{
      var lo, hi;
      if (isKcal) {{
        lo = fmtKcal(cs.edges[i]);
        hi = fmtKcal(cs.edges[i+1]);
      }} else if (isPct) {{
        lo = (cs.edges[i] * 100).toFixed(1) + "%";
        hi = (cs.edges[i+1] * 100).toFixed(1) + "%";
      }} else if (isInt) {{
        lo = Math.round(cs.edges[i]);
        hi = Math.round(cs.edges[i+1]);
      }} else {{
        lo = cs.edges[i].toFixed(2);
        hi = cs.edges[i+1].toFixed(2);
      }}
      html += '<div class="legend-item"><div class="legend-swatch" style="background:' + cs.colors[i] + '"></div>' + lo + ' - ' + hi + '</div>';
    }}
    html += '<div class="legend-item"><div class="legend-swatch" style="background:#d3d3d3"></div>No data</div>';
  }}

  document.getElementById("legendPanel").innerHTML = html;
}}

function updateMap() {{
  var indexKey = document.getElementById("indexSelect").value;
  var irrFilter = document.getElementById("irrSelect").value;
  var coconutMode = document.getElementById("coconutSelect").value;

  // Show/hide coconut dropdown - only relevant for quadrant layer
  var coconutRow = document.getElementById("coconutSelect").parentElement;
  // Always visible, but label indicates relevance

  var titleSuffix = "";
  if (indexKey === "kcal_diversity_quadrant" && coconutMode === "excluding") {{
    titleSuffix = " (excl. Coconut)";
  }}
  document.getElementById("mapTitle").innerHTML = "Calorie-Diversity Analysis: " + indexLabels[indexKey] + titleSuffix;

  var filtered = {{type: "FeatureCollection", features: []}};
  for (var i = 0; i < geojsonData.features.length; i++) {{
    var f = geojsonData.features[i];
    var irr = f.properties.irrigation_regime || "Unknown";
    if (irrFilter === "All" || irr.indexOf(irrFilter) !== -1) {{
      filtered.features.push(f);
    }}
  }}

  if (currentLayer) {{
    window._map.removeLayer(currentLayer);
  }}

  var isCateg = (indexKey === "kcal_diversity_quadrant");
  var cs = isCateg ? null : colorScales[indexKey];

  // Determine which quadrant property to use based on coconut mode
  var quadProp = (coconutMode === "excluding") ? "kcal_diversity_quadrant_ex_coconut" : "kcal_diversity_quadrant";

  currentLayer = L.geoJson(filtered, {{
    style: function(feature) {{
      var fillColor;
      if (isCateg) {{
        var q = feature.properties[quadProp] || "No Data";
        fillColor = quadColors[q] || "#d3d3d3";
      }} else {{
        var val = feature.properties[indexKey];
        fillColor = valToColor(val, cs.edges, cs.colors);
      }}
      return {{
        fillColor: fillColor,
        weight: 0.5,
        color: "#888",
        fillOpacity: 0.8
      }};
    }},
    onEachFeature: function(feature, layer) {{
      layer.bindTooltip(feature.properties.tooltip, {{
        sticky: true,
        direction: "auto",
        className: "district-tooltip"
      }});
      layer.on({{
        mouseover: function(e) {{
          e.target.setStyle({{weight: 2, color: "#333"}});
          e.target.bringToFront();
        }},
        mouseout: function(e) {{
          currentLayer.resetStyle(e.target);
        }}
      }});
    }}
  }}).addTo(window._map);

  updateLegend(indexKey);
}}

setTimeout(function() {{
  document.querySelectorAll('[class*="folium-map"]').forEach(function(el) {{
    var mapId = el.id;
    if (mapId && window[mapId]) {{
      window._map = window[mapId];
    }}
  }});
  if (!window._map) {{
    for (var key in window) {{
      try {{
        if (window[key] instanceof L.Map) {{
          window._map = window[key];
          break;
        }}
      }} catch(e) {{}}
    }}
  }}
  if (window._map) {{
    updateMap();
  }} else {{
    console.error("Could not find Leaflet map instance");
  }}
}}, 500);
</script>
"""

m.get_root().html.add_child(folium.Element(custom_html))

# ---------------------------------------------------------------------------
# 6. Save and open
# ---------------------------------------------------------------------------
OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
m.save(str(OUT_PATH))
print(f"\nMap saved to: {OUT_PATH}")
print(f"Opening in browser...")
webbrowser.open(str(OUT_PATH))
