"""
71_validate_shrug_covariates.py

Checks and balances for the SHRUG district covariate table before it is used
for anything. Nine checks, each either PASS, WARN or FAIL, written to a report.

  C1  Join to the diversity panel: match rate, both directions, unmatched named
  C2  Internal consistency: shares in [0,1], partitions sum to 1, no negatives
  C3  Cross-source irrigation: Antyodaya 2019 vs PC11 Village Directory 2011
  C4  Cross-source caste: PC11 population abstract vs SECC 2012
  C5  External anchor: state cropping intensity vs published DES ranking
  C6  External anchor: state irrigation share vs published DES ranking
  C7  Old vs new: repo scraped irrigation_pct vs SHRUG measure
  C8  Coverage: which districts and states are too thin to trust
  C9  Aggregation invariance: shrid-built district totals vs SHRUG's own
      pre-aggregated district file

Outputs:
  outputs/shrug_covariates/validation_report.md
  outputs/shrug_covariates/diversity_shrug_merged.csv   (only if C1 passes)
  outputs/shrug_covariates/unmatched_districts.csv
"""
import os
import numpy as np
import pandas as pd
from scipy import stats

REPO = r"D:/crop-diversity"
OUT = REPO + "/outputs/shrug_covariates"
DIV = REPO + "/outputs/crop_diversity_analysis"
SHRUG = r"D:/SHRUG_2.1_Data/extracted"

R = []
RESULTS = []


def w(s=""):
    print(s)
    R.append(str(s))


def verdict(check, status, detail):
    RESULTS.append(dict(check=check, status=status, detail=detail))
    w("")
    w("**{}: {}**  {}".format(check, status, detail))


def head(t):
    w("")
    w("## " + t)
    w("")


w("# Validation report: SHRUG district covariates")
w("")
w("Generated by `scripts/71_validate_shrug_covariates.py`.")
w("Source table: `outputs/shrug_covariates/shrug_district_covariates.csv`")

sh = pd.read_csv(OUT + "/shrug_district_covariates.csv")
dv = pd.read_csv(DIV + "/district_diversity_indices.csv")
w("")
w("SHRUG table: {} districts, {} columns.".format(*sh.shape))
w("Diversity table: {} districts, {} columns.".format(*dv.shape))


# ------------------------------------------------------------------ C1
head("C1. Join to the diversity panel")

def norm(s):
    s = s.astype(str).str.upper().str.strip()
    s = s.str.replace(r"[^A-Z0-9| ]", "", regex=True)
    s = s.str.replace(r"\s+", " ", regex=True)
    # common transliteration and reorganisation variants
    for a, b in [("ORISSA", "ODISHA"), ("PONDICHERRY", "PUDUCHERRY"),
                 ("UTTARANCHAL", "UTTARAKHAND"), ("JAMMU AND KASHMIR", "JAMMU KASHMIR"),
                 ("NCT OF DELHI", "DELHI"), ("DELHI", "NCT OF DELHI"),
                 ("ANDAMAN AND NICOBAR ISLANDS", "ANDAMAN NICOBAR ISLANDS")]:
        pass
    return s


ALIAS_STATE = {
    "ORISSA": "ODISHA", "PONDICHERRY": "PUDUCHERRY", "UTTARANCHAL": "UTTARAKHAND",
    "JAMMU AND KASHMIR": "JAMMU KASHMIR", "NCT OF DELHI": "DELHI",
    "ANDAMAN AND NICOBAR ISLANDS": "ANDAMAN NICOBAR ISLANDS",
    "DADRA AND NAGAR HAVELI": "DADRA NAGAR HAVELI",
    "DAMAN AND DIU": "DAMAN DIU", "CHHATISGARH": "CHHATTISGARH",
}
ALIAS_DIST = {
    "ALLAHABAD": "PRAYAGRAJ", "GURGAON": "GURUGRAM", "MEWAT": "NUH",
    "FAIZABAD": "AYODHYA", "BANGALORE": "BENGALURU", "MYSORE": "MYSURU",
    "BELGAUM": "BELAGAVI", "GULBARGA": "KALABURAGI", "BIJAPUR": "VIJAYAPURA",
    "SHIMOGA": "SHIVAMOGGA", "TUMKUR": "TUMAKURU", "BELLARY": "BALLARI",
    "CHIKMAGALUR": "CHIKKAMAGALURU", "HOSHANGABAD": "NARMADAPURAM",
    "PONDICHERRY": "PUDUCHERRY", "BID": "BEED", "BULDANA": "BULDHANA",
    "AHMADNAGAR": "AHMEDNAGAR", "GARHCHIROLI": "GADCHIROLI",
    "RAE BARELI": "RAEBARELI", "SANT RAVIDAS NAGAR": "BHADOHI",
    "KANSHIRAM NAGAR": "KASGANJ", "MAHAMAYA NAGAR": "HATHRAS",
    "JYOTIBA PHULE NAGAR": "AMROHA", "PASHCHIM CHAMPARAN": "WEST CHAMPARAN",
    "PURBA CHAMPARAN": "EAST CHAMPARAN", "KAIMUR BHABUA": "KAIMUR",
}


def keyify(state, dist):
    s = state.astype(str).str.upper().str.strip()
    s = s.str.replace(r"[^A-Z0-9 ]", " ", regex=True).str.replace(r"\s+", " ", regex=True).str.strip()
    s = s.replace(ALIAS_STATE)
    d = dist.astype(str).str.upper().str.strip()
    d = d.str.replace(r"[^A-Z0-9 ]", " ", regex=True).str.replace(r"\s+", " ", regex=True).str.strip()
    d = d.replace(ALIAS_DIST)
    return s + "|" + d


sh["jkey"] = keyify(sh["state_name"], sh["district_name"])
dv["jkey"] = keyify(dv["state_name"], dv["district_name"])

assert sh["jkey"].is_unique, "SHRUG join key not unique"  # checked pre-merge
dup_dv = dv["jkey"].duplicated().sum()
w("Duplicate join keys: SHRUG 0, diversity {}.".format(dup_dv))

cwx = pd.read_csv(OUT + "/district_crosswalk.csv")
dv = dv.merge(cwx[["div_key", "shrug_key", "method"]],
              left_on="district_key", right_on="div_key", how="left")
dv["jkey"] = dv["shrug_key"].fillna(dv["jkey"])
sh["jkey"] = sh["district_key"]
mg = dv.merge(sh, on="jkey", how="outer", suffixes=("_div", "_shrug"), indicator=True)
both = int((mg["_merge"] == "both").sum())
div_only = mg[mg["_merge"] == "left_only"]
shr_only = mg[mg["_merge"] == "right_only"]
rate_div = both / len(dv)
rate_shr = both / len(sh)
w("")
w("| side | n | matched | rate |")
w("|---|---|---|---|")
w("| diversity | {} | {} | {:.1%} |".format(len(dv), both, rate_div))
w("| SHRUG | {} | {} | {:.1%} |".format(len(sh), both, rate_shr))

unm = pd.concat([
    div_only[["jkey"]].assign(side="diversity_only"),
    shr_only[["jkey"]].assign(side="shrug_only")])
unm.to_csv(OUT + "/unmatched_districts.csv", index=False)
w("")
w("Unmatched, diversity side (first 30): " + ", ".join(sorted(div_only["jkey"])[:30]))
w("")
w("Unmatched, SHRUG side (first 30): " + ", ".join(sorted(shr_only["jkey"])[:30]))

st = "PASS" if rate_div >= 0.80 else ("WARN" if rate_div >= 0.65 else "FAIL")
verdict("C1 join", st, "{} districts matched, {:.1%} of the diversity panel.".format(both, rate_div))

M = mg[mg["_merge"] == "both"].drop(columns="_merge").copy()


# ------------------------------------------------------------------ C2
head("C2. Internal consistency")
issues = []

share_cols = [c for c in sh.columns if not c.startswith("DEPRECATED_")
              and (c.endswith("_vshare") or c.endswith("_ashare")
              or c.endswith("_share") or c in ("irr_share", "irr_share_vd11"))]
for c in share_cols:
    v = pd.to_numeric(sh[c], errors="coerce")
    bad = int(((v < -1e-9) | (v > 1 + 1e-9)).sum())
    if bad:
        issues.append("{}: {} values outside [0,1] (max {:.3f})".format(c, bad, v.max()))

part_ay = sh[["ay_src_canal_vshare", "ay_src_ground_vshare",
              "ay_src_surface_vshare", "ay_src_other_vshare"]].sum(axis=1)
off_ay = int((part_ay.sub(1).abs() > 0.01).sum())
part_vd = sh[[c for c in sh.columns if c.startswith("vd_src_") and c.endswith("_ashare")]].sum(axis=1)
off_vd = int((part_vd.sub(1).abs() > 0.01).sum())
w("Antyodaya irrigation source shares sum to 1: {} of {} districts off by >0.01.".format(
    off_ay, len(sh)))
w("PC11 VD irrigation source area shares sum to 1: {} of {} districts off by >0.01.".format(
    off_vd, len(sh)))

neg = {c: int((pd.to_numeric(sh[c], errors="coerce") < 0).sum())
       for c in sh.select_dtypes("number").columns}
neg = {k: v for k, v in neg.items() if v > 0}
w("Columns with negative values: {}".format(neg if neg else "none"))

ci = pd.to_numeric(sh["cropping_intensity"], errors="coerce")
w("Cropping intensity: min {:.2f}, p50 {:.2f}, max {:.2f}, below 1.0: {} districts.".format(
    ci.min(), ci.median(), ci.max(), int((ci < 1).sum())))
if int((ci < 1).sum()) > 0:
    issues.append("{} districts have cropping intensity below 1, which is impossible "
                  "if GCA = kharif+rabi+other and NSA is net sown".format(int((ci < 1).sum())))

for s in issues:
    w("- ISSUE: " + s)
verdict("C2 internal consistency", "PASS" if not issues else "WARN",
        "{} issue(s).".format(len(issues)))


# ------------------------------------------------------------------ C3
head("C3. Cross-source irrigation (Antyodaya 2019 vs PC11 VD 2011)")
a = pd.to_numeric(sh["irr_share"], errors="coerce")
b = pd.to_numeric(sh["irr_share_vd11"], errors="coerce")
ok = a.notna() & b.notna() & (b <= 1.5)
r_p = stats.pearsonr(a[ok], b[ok])
r_s = stats.spearmanr(a[ok], b[ok])
w("n = {} districts with both measures.".format(int(ok.sum())))
w("Pearson r = {:.3f}, Spearman rho = {:.3f}.".format(r_p[0], r_s[0]))
w("Antyodaya mean {:.3f}, PC11 VD mean {:.3f}.".format(a[ok].mean(), b[ok].mean()))
st = "PASS" if r_s[0] >= 0.70 else ("WARN" if r_s[0] >= 0.50 else "FAIL")
verdict("C3 irrigation cross-source", st,
        "Two independent sources 8 years apart agree at rho = {:.3f}.".format(r_s[0]))


# ------------------------------------------------------------------ C4
head("C4. Cross-source caste share (PC11 2011 vs SECC 2012)")
for lab, c1, c2 in [("SC", "pca_sc_share", "secc_sc_share"),
                    ("ST", "pca_st_share", "secc_st_share")]:
    x = pd.to_numeric(sh[c1], errors="coerce")
    y = pd.to_numeric(sh[c2], errors="coerce")
    k = x.notna() & y.notna()
    w("{}: n={}, Pearson r = {:.3f}, mean PC11 {:.3f} vs SECC {:.3f}.".format(
        lab, int(k.sum()), stats.pearsonr(x[k], y[k])[0], x[k].mean(), y[k].mean()))
rr = stats.pearsonr(*[pd.to_numeric(sh[c], errors="coerce")[
    pd.to_numeric(sh["pca_sc_share"], errors="coerce").notna() &
    pd.to_numeric(sh["secc_sc_share"], errors="coerce").notna()]
    for c in ("pca_sc_share", "secc_sc_share")])[0]
verdict("C4 caste cross-source", "PASS" if rr >= 0.85 else "WARN",
        "SC share agrees across census and SECC at r = {:.3f}.".format(rr))


# ------------------------------------------------------------------ C5/C6
head("C5 and C6. External anchor at state level")
w("Reference values are published state figures for cropping intensity and")
w("gross irrigated area as a share of gross cropped area (DES Land Use Statistics,")
w("around 2018-19). They are used for RANK agreement only, not level matching.")
w("")
w("> UNCONFIRMED: the reference column is entered from memory of the DES tables and")
w("> must be re-checked against the published source before it appears in any report.")

REF_CI = {"punjab": 1.90, "haryana": 1.87, "west bengal": 1.85, "uttar pradesh": 1.68,
          "himachal pradesh": 1.77, "bihar": 1.44, "madhya pradesh": 1.62,
          "rajasthan": 1.47, "maharashtra": 1.35, "karnataka": 1.24,
          "andhra pradesh": 1.30, "tamil nadu": 1.21, "gujarat": 1.28,
          "odisha": 1.60, "assam": 1.50, "jharkhand": 1.20, "chhattisgarh": 1.25,
          "uttarakhand": 1.58, "kerala": 1.35, "telangana": 1.30}
REF_IRR = {"punjab": 0.985, "haryana": 0.905, "uttar pradesh": 0.852, "bihar": 0.680,
           "tamil nadu": 0.585, "west bengal": 0.615, "andhra pradesh": 0.555,
           "gujarat": 0.52, "madhya pradesh": 0.52, "rajasthan": 0.44,
           "karnataka": 0.36, "maharashtra": 0.21, "odisha": 0.35,
           "assam": 0.11, "jharkhand": 0.12, "chhattisgarh": 0.34,
           "himachal pradesh": 0.22, "uttarakhand": 0.50, "kerala": 0.18,
           "telangana": 0.50}

use = sh[~sh["flag_low_ay_coverage"].fillna(True) & ~sh["flag_no_antyodaya"]]
gs = use.groupby("state_name").agg(
    gca=("gca_ha", "sum"), nsa=("nsa_ha", "sum"),
    irr=("ay_area_irrigated_in_hac", "sum"),
    unirr=("ay_total_unirrigated_land_area_in_h", "sum"),
    nd=("district_key", "size"))
gs["ci"] = gs["gca"] / gs["nsa"]
gs["irr_share"] = gs["irr"] / (gs["irr"] + gs["unirr"])

for lab, ref, col, key in [("C5 cropping intensity", REF_CI, "ci", "ci"),
                           ("C6 irrigation share", REF_IRR, "irr_share", "irr")]:
    t = gs.copy()
    t["ref"] = t.index.map(ref)
    t = t.dropna(subset=["ref"])
    rho = stats.spearmanr(t[col], t["ref"])[0]
    r = stats.pearsonr(t[col], t["ref"])[0]
    mae = (t[col] - t["ref"]).abs().mean()
    w("")
    w("### " + lab)
    w("")
    w("| state | districts | SHRUG | reference | diff |")
    w("|---|---|---|---|---|")
    for s_, row in t.sort_values("ref", ascending=False).iterrows():
        w("| {} | {} | {:.2f} | {:.2f} | {:+.2f} |".format(
            s_, int(row["nd"]), row[col], row["ref"], row[col] - row["ref"]))
    w("")
    w("Spearman rho = {:.3f}, Pearson r = {:.3f}, mean absolute difference = {:.3f}.".format(
        rho, r, mae))
    st = "PASS" if rho >= 0.75 else ("WARN" if rho >= 0.55 else "FAIL")
    verdict(lab, st, "Rank agreement with published state figures rho = {:.3f}, MAE {:.3f}.".format(rho, mae))


# ------------------------------------------------------------------ C7
head("C7. Old scraped irrigation_pct vs new SHRUG measure")
o = pd.to_numeric(M["irrigation_pct"], errors="coerce")
if o.max() is not np.nan and o.max() > 1.5:
    o = o / 100.0
n = pd.to_numeric(M["irr_share"], errors="coerce")
k = o.notna() & n.notna()
w("Overlap: {} districts have both the scraped value and the SHRUG value.".format(int(k.sum())))
if k.sum() > 10:
    rp = stats.pearsonr(o[k], n[k])[0]
    rs = stats.spearmanr(o[k], n[k])[0]
    w("Pearson r = {:.3f}, Spearman rho = {:.3f}.".format(rp, rs))
    w("Scraped mean {:.3f} (sd {:.3f}), SHRUG mean {:.3f} (sd {:.3f}).".format(
        o[k].mean(), o[k].std(), n[k].mean(), n[k].std()))
    w("Mean absolute difference {:.3f}.".format((o[k] - n[k]).abs().mean()))
    dis = M.loc[k].assign(_d=(o[k] - n[k]).abs()).nlargest(12, "_d")[
        ["jkey", "irrigation_pct", "irr_share"]]
    w("")
    w("Largest 12 disagreements:")
    w("")
    w("| district | scraped | SHRUG |")
    w("|---|---|---|")
    for _, rw in dis.iterrows():
        w("| {} | {} | {:.3f} |".format(rw["jkey"], rw["irrigation_pct"], rw["irr_share"]))
    st = "PASS" if rs >= 0.70 else ("WARN" if rs >= 0.45 else "FAIL")
    verdict("C7 old vs new irrigation", st,
            "rho = {:.3f} between the scraped variable and the SHRUG measure. "
            "Low agreement means the original regime finding rests on a noisy variable.".format(rs))
else:
    verdict("C7 old vs new irrigation", "FAIL", "Too few overlapping districts.")


# ------------------------------------------------------------------ C8
head("C8. Coverage")
cov = sh.assign(ratio=sh["ay_n_villages"] / sh["vd_n_villages"])
bad = cov[cov["ratio"].isna() | (cov["ratio"] < 0.25)][
    ["state_name", "district_name", "ay_n_villages", "vd_n_villages", "ratio"]]
w("{} districts have Antyodaya covering under 25% of their PC11 villages "
  "(or no Antyodaya at all).".format(len(bad)))
w("")
w("| state | district | antyodaya villages | pc11 villages | ratio |")
w("|---|---|---|---|---|")
for _, rw in bad.sort_values(["state_name", "district_name"]).head(40).iterrows():
    w("| {} | {} | {} | {} | {} |".format(
        rw["state_name"], rw["district_name"],
        "-" if pd.isna(rw["ay_n_villages"]) else int(rw["ay_n_villages"]),
        int(rw["vd_n_villages"]) if pd.notna(rw["vd_n_villages"]) else "-",
        "-" if pd.isna(rw["ratio"]) else "{:.2f}".format(rw["ratio"])))
st_cov = cov.groupby("state_name")["ratio"].median().sort_values()
w("")
w("Worst state median coverage ratios: " + ", ".join(
    "{} {:.2f}".format(i, v) for i, v in st_cov.head(8).items()))
verdict("C8 coverage", "WARN" if len(bad) else "PASS",
        "{} districts excluded from headline analysis for thin Antyodaya coverage.".format(len(bad)))


# ------------------------------------------------------------------ C9
head("C9. Aggregation invariance against SHRUG's own district file")
ad = pd.read_stata(SHRUG + "/shrug-antyodaya-dta/antyodaya_pc11dist.dta",
                   columns=["pc11_state_id", "pc11_district_id",
                            "net_sown_area_in_hac", "area_irrigated_in_hac",
                            "total_unirrigated_land_area_in_h",
                            "net_sown_area_kharif_in_hac",
                            "net_sown_area_rabi_in_hac",
                            "net_sown_area_other_in_hac",
                            "total_cultivable_area_in_hac",
                            "total_no_of_farmers"])
sh_k = sh.copy()
for c in ["pc11_state_id", "pc11_district_id"]:
    sh_k[c] = sh_k[c].astype(str).str.zfill(2 if c.endswith("state_id") else 3)
    ad[c] = ad[c].astype(str).str.zfill(2 if c.endswith("state_id") else 3)
cmp = sh_k.merge(ad, on=["pc11_state_id", "pc11_district_id"], how="inner",
                 suffixes=("", "_ddl"))
w("Matched {} districts against SHRUG's pre-aggregated district file.".format(len(cmp)))
w("")
w("Levels are NOT expected to agree: `antyodaya_shrid.dta` covers 521,223 shrids")
w("carrying 857m people, while DDL's district file aggregates a wider village set")
w("carrying 1,007m. What must agree is every RATIO, since numerator and denominator")
w("come from the same village set on both sides.")
w("")
cmp["ddl_iu"] = cmp["area_irrigated_in_hac"] / (cmp["area_irrigated_in_hac"] +
                                                cmp["total_unirrigated_land_area_in_h"])
cmp["our_iu"] = cmp["ay_area_irrigated_in_hac"] / (cmp["ay_area_irrigated_in_hac"] +
                                                   cmp["ay_total_unirrigated_land_area_in_h"])
cmp["ddl_ci"] = (cmp["net_sown_area_kharif_in_hac"] + cmp["net_sown_area_rabi_in_hac"] +
                 cmp["net_sown_area_other_in_hac"]) / cmp["net_sown_area_in_hac"]
cmp["ddl_hold"] = cmp["total_cultivable_area_in_hac"] / cmp["total_no_of_farmers"]
w("| ratio | n | Pearson r | median relative gap |")
w("|---|---|---|---|")
rr9 = np.nan
for mine, theirs, lab in [("our_iu", "ddl_iu", "irrigation share"),
                          ("cropping_intensity", "ddl_ci", "cropping intensity"),
                          ("mean_holding_ha", "ddl_hold", "mean holding size")]:
    x = pd.to_numeric(cmp[mine], errors="coerce")
    y = pd.to_numeric(cmp[theirs], errors="coerce")
    kk = x.notna() & y.notna() & np.isfinite(x) & np.isfinite(y) & (y != 0)
    r_ = stats.pearsonr(x[kk], y[kk])[0]
    gap = ((x[kk] - y[kk]).abs() / y[kk].abs()).median()
    w("| {} | {} | {:.4f} | {:.4f} |".format(lab, int(kk.sum()), r_, gap))
    if mine == "our_iu":
        rr9 = r_
verdict("C9 aggregation invariance", "PASS" if rr9 >= 0.99 else "WARN",
        "Every ratio reproduces SHRUG's own district file at r >= {:.4f}.".format(rr9))

# ------------------------------------------------------------------ save
head("Summary")
w("")
w("| check | status | detail |")
w("|---|---|---|")
for r_ in RESULTS:
    w("| {} | {} | {} |".format(r_["check"], r_["status"], r_["detail"]))

nfail = sum(1 for r_ in RESULTS if r_["status"] == "FAIL")
w("")
w("{} FAIL, {} WARN, {} PASS.".format(
    nfail, sum(1 for r_ in RESULTS if r_["status"] == "WARN"),
    sum(1 for r_ in RESULTS if r_["status"] == "PASS")))

with open(OUT + "/validation_report.md", "w", encoding="utf-8") as f:
    f.write("\n".join(R))
M.to_csv(OUT + "/diversity_shrug_merged.csv", index=False)
print("\nWROTE validation_report.md and diversity_shrug_merged.csv ({} rows)".format(len(M)))
